Context
cassemanagement/case-management-ui pull request #5
Opened 2020-12-01 15:54 UTC by battmeech

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] Any dependent changes have been merged and published in downstream modules

2020-12-01 17:56 UTC, jcassem requested changes
Worth reviewing our approach to LinkContext before merging.

2020-12-01 17:56 UTC, jcassem commented on src/pages/EntityPage.tsx
> +    //document.title = entity?.name ?? 'Entity';
remove

2020-12-01 17:56 UTC, jcassem commented on src/context/links/LinksContext.tsx
> +                .then((payload) => {
Do we need context/reducers for this? We do need this function to be called on the `EntityPage` but technically we would only add/create or remove links from there rather than bulk update the entire thing.

2020-12-01 17:56 UTC, jcassem commented on src/pages/EntityPage.tsx
> +function Toolbar(props: {
This is much neater

2020-12-02 09:48 UTC, battmeech commented on src/context/links/LinksContext.tsx
> +                .then((payload) => {
It's quite handy, as the links are used in the graph & links table

2020-12-02 09:51 UTC, merged